version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build:
      context: .
      args:
        - BINARY_PATH
    image: malteneuss/workler
#    depends_on:
#      - db
#    command: /opt/myapp/workler
    ports:
      - '3000:3000'
volumes:
  db:
