resolver: lts-18.28

allow-newer: true
packages:
- .
extra-deps:
  - classy-prelude-yesod-1.5.0
#  - classy-prelude-yesod-1.5.0@sha256:8f7e183bdfd6d2ea9674284c4f285294ab086aff60d9be4e5d7d2f3c1a2b05b7,1330
  - happy-1.20.0

system-ghc: true

#local-bin-path: dist

